store:
  host: "127.0.0.1"
  port: 5432
  username: "solana"
  password: "1111"
  schema: "solana"

contract:
  l2_message_program_id: "4yNGxshZTzeSv6ZLSBwNGfDfZyCEbxtmW4MvRWCEoAmy"

chain:
  url: "http://127.0.0.1:8899"
  fraud_proof_native_program_id: ""
  #  keypair base58 string
  execute_keypair: ""
  l1_root_mgr_program_id: "8s5HysGMiK7eht7MBM7XMQeTuKr5sEyafYkscziHHS73"
  l1_slots_account_pubkey: "CRQSHYJQjJcLMurc5orYk7V68eHjLbQaBQUL49E7nwFc"
