store:
  host: "127.0.0.1"
  port: 5432
  username: "solana"
  password: "1111"
  schema: "solana"

contract:
  l2_message_program_id: ""
  l2_message_fund_account_pubkey: ""
  system_program_id: "11111111111111111111111111111111"

chain:
  url: "http://127.0.0.1:8899"
  fraud_proof_native_program_id: ""
  #  keypair base58 string
  execute_keypair: ""
  l1_root_mgr_program_id: ""
  l1_slots_account_pubkey: ""
